/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 21/02/2018 09:12:47
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            25000000
#define MX_EXTERNAL_CLOCK_VALUE                 12288000
#define MX_PLLCLKFreq_Value                     120000000
#define MX_SYSCLKFreq_VALUE                     120000000
#define MX_HCLKFreq_Value                       120000000
#define MX_FCLKCortexFreq_Value                 120000000
#define MX_CortexFreq_Value                     120000000
#define MX_AHBFreq_Value                        120000000
#define MX_APB1Freq_Value                       30000000
#define MX_APB2Freq_Value                       60000000
#define MX_APB1TimFreq_Value                    60000000
#define MX_APB2TimFreq_Value                    120000000
#define MX_48MHZClocksFreq_Value                48000000
#define MX_EthernetFreq_Value                   120000000
#define MX_I2SClocksFreq_Value                  96000000
#define MX_RTCFreq_Value                        32000
#define MX_WatchDogFreq_Value                   32000
#define MX_MCO1PinFreq_Value                    16000000
#define MX_MCO2PinFreq_Value                    120000000

/*-------------------------------- ADC3       --------------------------------*/

#define MX_ADC3                                 1

/* GPIO Configuration */

/* Pin PF9 */
#define MX_ADC3_IN7_Pin                         PF9
#define MX_ADC3_IN7_GPIOx                       GPIOF
#define MX_ADC3_IN7_GPIO_PuPd                   GPIO_NOPULL
#define MX_ADC3_IN7_GPIO_Pin                    GPIO_PIN_9
#define MX_ADC3_IN7_GPIO_Mode                   GPIO_MODE_ANALOG

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PC13 */
#define MX_PC13_Pin                             PC13
#define MX_PC13_GPIOx                           GPIOC
#define MX_PC13_GPIO_PuPd                       GPIO_NOPULL
#define MX_PC13_GPIO_Pin                        GPIO_PIN_13
#define MX_PC13_GPIO_Mode                       GPIO_MODE_INPUT

/* Pin PG8 */
#define MX_PG8_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PG8_Pin                              PG8
#define MX_PG8_GPIOx                            GPIOG
#define MX_PG8_PinState                         GPIO_PIN_RESET
#define MX_PG8_GPIO_PuPd                        GPIO_NOPULL
#define MX_PG8_GPIO_Pin                         GPIO_PIN_8
#define MX_PG8_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PG7 */
#define MX_PG7_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PG7_Pin                              PG7
#define MX_PG7_GPIOx                            GPIOG
#define MX_PG7_PinState                         GPIO_PIN_RESET
#define MX_PG7_GPIO_PuPd                        GPIO_NOPULL
#define MX_PG7_GPIO_Pin                         GPIO_PIN_7
#define MX_PG7_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PA0-WKUP */
#define MX_PA0_WKUP_Pin                         PA0_WKUP
#define MX_PA0_WKUP_GPIOx                       GPIOA
#define MX_PA0_WKUP_GPIO_PuPd                   GPIO_NOPULL
#define MX_PA0_WKUP_GPIO_Pin                    GPIO_PIN_0
#define MX_PA0_WKUP_GPIO_Mode                   GPIO_MODE_INPUT

/* Pin PH3 */
#define MX_PH3_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PH3_Pin                              PH3
#define MX_PH3_GPIOx                            GPIOH
#define MX_PH3_PinState                         GPIO_PIN_RESET
#define MX_PH3_GPIO_PuPd                        GPIO_NOPULL
#define MX_PH3_GPIO_Pin                         GPIO_PIN_3
#define MX_PH3_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PH2 */
#define MX_PH2_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PH2_Pin                              PH2
#define MX_PH2_GPIOx                            GPIOH
#define MX_PH2_PinState                         GPIO_PIN_RESET
#define MX_PH2_GPIO_PuPd                        GPIO_NOPULL
#define MX_PH2_GPIO_Pin                         GPIO_PIN_2
#define MX_PH2_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PI10 */
#define MX_PI10_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PI10_Pin                             PI10
#define MX_PI10_GPIOx                           GPIOI
#define MX_PI10_PinState                        GPIO_PIN_RESET
#define MX_PI10_GPIO_PuPd                       GPIO_NOPULL
#define MX_PI10_GPIO_Pin                        GPIO_PIN_10
#define MX_PI10_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PG15 */
#define MX_PG15_Pin                             PG15
#define MX_PG15_GPIOx                           GPIOG
#define MX_PG15_GPIO_PuPd                       GPIO_NOPULL
#define MX_PG15_GPIO_Pin                        GPIO_PIN_15
#define MX_PG15_GPIO_Mode                       GPIO_MODE_INPUT

/* Pin PG6 */
#define MX_PG6_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PG6_Pin                              PG6
#define MX_PG6_GPIOx                            GPIOG
#define MX_PG6_PinState                         GPIO_PIN_RESET
#define MX_PG6_GPIO_PuPd                        GPIO_NOPULL
#define MX_PG6_GPIO_Pin                         GPIO_PIN_6
#define MX_PG6_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PH7 */
#define MX_PH7_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PH7_Pin                              PH7
#define MX_PH7_GPIOx                            GPIOH
#define MX_PH7_PinState                         GPIO_PIN_RESET
#define MX_PH7_GPIO_PuPd                        GPIO_NOPULL
#define MX_PH7_GPIO_Pin                         GPIO_PIN_7
#define MX_PH7_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PH6 */
#define MX_PH6_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PH6_Pin                              PH6
#define MX_PH6_GPIOx                            GPIOH
#define MX_PH6_PinState                         GPIO_PIN_RESET
#define MX_PH6_GPIO_PuPd                        GPIO_NOPULL
#define MX_PH6_GPIO_Pin                         GPIO_PIN_6
#define MX_PH6_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

#endif  /* __MX_DEVICE_H */

